[package]
name = "tx-processor"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
nutype = { version = "0.7.0", features = ["serde"] }
rust_decimal = { version = "1.42.1", features = ["serde-with-str"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.19"

[dev-dependencies]
proptest = "1.11.0"
